### ISSUE TITLE
Add/remove cards from roll screen

### ISSUE THREAD

**Issue by ebanDev** [ramzan/dicegainz#2]
Hi ! Thank you for this amazing app ! I'd like to have an option to add lifts 🙏🏻

**Comment by ramzan** [comment]
Hey, glad you like it! In the Lifts tab, there should be a "+" button at the bottom of the screen that allows you to create lifts.

**Comment by ebanDev** [comment]
I think I didn't explain well 😁. On this screen I would like to
 have an option to add lifts... ![Screenshot_20201207-080943_Dice_Gainz](https://user-images.githubusercontent.com/57091497/101320277-c69c9380-3863-11eb-8de9-8ab37b07d942.png)

**Comment by ramzan** [comment]
I see. Seeing as it's only a single swipe to get to the new lift button, I think creating lifts from this screen is unnecessary. But thanks for your interest!

**Comment by ebanDev** [comment]
I was talking about the lift cards... I'd like to have an option to add more cards (see on the screenshot)
![Screenshot_20201208-075906_Dice_Gainz-01](https://user-images.githubusercontent.com/57091497/101451117-e8614d80-392b-11eb-987d-d2971a5ef7d8.jpeg)

**Comment by ebanDev** [comment]
Only three cards are not enough for me 😁

**Comment by ramzan** [comment]
Oh OK. I'm a bit busy at the moment but maybe sometime in the future. Any pull requests are welcome.

**Comment by ebanDev** [comment]
Okay !
